---
title: "Exploratory Analysis"
output: html_document
---

## Project title

NBA & WNBA Player Statistical Analysis

### Authors

Binyam Kebede

### Date

Spring 2024

### Abstract

No more than three sentences that summarize your project. Focus on the very most important aspects. For example: (1) "Our main question is .... This question is important because .... To address the question, we will ...." (2) "We are concerned with ..., because .... To address this concern, we plan to ...." (3) "Consider that .... This is important because .... Accordingly, we plan to ...."

Our main question is how do individual player statistics impact team performance? This question is important because it helps us understand the relationship individual performance
has with team success. Accordingly, we plan to create a detailed analysis on each player statistic, by comparing and visualizing these stats, we gain insights into player performance
and team dynamics.

### Keywords

3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")
Individual statistics/performance, Player analysis, and Team success
### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

In the world of professional basketball, knowing statistics is everything when it comes to team success. From the players themselves to the coaches and even other opposing teams 
information on player performance is crucial to player improvement and for teams making successful game plans and strategies for their success. This project explores the relationship
between  individual player metrics and team outcomes. By analyzing data from both the NBA and WNBA we aim to answer these important questions:

1. How does individual performance affect team success? 

This question investigates the statistics of player in different categories like points per game, assists, rebounds, etc.. and inspect their influence on overall team success.

2. What position makes the most impact on a team's success?

This question looks at each position, comparing them to each other to find the most impactful position.


3. Are there statistical difference between the NBA and WNBA players?

This question explores the data for both leagues and searches for any differential trends that could be based on gender or other potential factors.

4. Is there a correlation between a high free throw percentage of a team and it's success?

This question searches for a correlation between how well a teams free throw shooting contributes to a successful season.

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

In this project, we delve into the world of professional basketball, analyzing player statistics from both the NBA and WNBA. Our goal is to uncover insights that impact team performance,
inform coaching strategies, and guide decision-making. The first article dives into the multiple ways the NBA is currently leveraging data analytics to improve performance. It touches on
how teams are using player performance analysis data to optimize players' overall performance and create game strategies. They further explain how teams also used to scout other players
for implementing defensive and offensive game strategies, but also for scouting possible player acquisitions. The second article explores the most important stat in basketball and how
coaches use this to optimize their player's abilities and the team's success. The article states that efficiency is the most important statistic in basketball, they explain how efficiency
statistics are calculated and what the meaning behind the numbers is. The third article carries out a statistical comparison between the NBA and WNBA. It delves into the statistical
differences between the two leagues in the form of shot distributions, trajectories, and shooting percentages. It also includes multiple interactive charts and graphs to visualize the
comparisons.

**Works Cited**

1. Mahima Phalkey, "7 Ways NBA Teams Use Analytics for Performance Improvement", AlmaBetter, May 23, 2023, <https://www.almabetter.com/bytes/articles/how-nba-teams-use-data-analytics-to-improve-their-performance>

2. Kosta Tiodorovic, "Efficiency- The most important Stat in Basketball", BenchBoss, Sep 23, 2020, <https://benchboss.ai/efficiency-the-most-important-stat-in-basketball/>

3. Zoe Vernon, "Comparing the NBA and WNBA", Zoevernon.github.io, Aug 30, 2020, <https://zoevernon.github.io/posts/2020/08/nba-wnba-comparison/#:~:text=There%20are%20a%20number%20of,overall%20trends%20of%20those%20statistics.>

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)


The dataset used for this project comes from a combination of two data sets from the basketball reference website, one is the 2023-2024 season of the [NBA](https://www.basketball-reference.com/leagues/NBA_2023_per_game.html) and the other is the 2023 season of the [WNBA](https://www.basketball-reference.com/wnba/years/2023_per_game.html). The dataset was created by Sean Lahman and then used and modified by Basketball Reference. The data itself was
gathered by SportRadar, which is the official statistics provider for the NBA. It was collected for the NBA to provide both the teams and media platforms to provide real-time data to the
fans watching the games. This data set consists of 26 observations (rows) and 912 features (columns). There shouldn’t be any ethical questions or questions of power about how the data
was collected as it was collected using advanced technologies and reliable accomplished sports journalists, with no actual way to interfere with the data itself. A possible limitation of
this data is that not all players have data in each category, which might result in skewing data in certain directions. 

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

The findings of this project can have multiple implications for technologists, designers, and policymakers. The results of this analysis can be used by technologists to build different
statistic-driven tools to help create in-game strategies. Technologists can also use it to improve existing player-tracking technologies for both the NBA and WNBA. It can be used to
enhance these technologies by making use of the analysis results to capture more precise data. Graphic designers can create different visualizations of the player stats to be used for
broadcasting, player comparison tools, or other fan-related experiences. Policymakers can use this analysis to address current issues on player wage disparities between the NBA and WNBA.
Understanding the high performance of these players in both leagues can help promote equitable compensation for everyone. Policymakers in these leagues can use this analysis to change
the rules of the sport. A current issue discussed in the basketball world is how rules have changed a lot in recent years and as a result, it has brought conflict between players and
referees. In summary, this analysis can bring forth a lot of change in the world of basketball. It empowers changes in decision-making for both optimization of players performance and
promotes fair and equitable changes in policy-making.


### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)
Working with sports data there are several potential challenges and limitations.

Working with sports data there are several potential challenges and limitations. A Player’s performance can be impacted by external factors such as injuries, playing time, and other
extenuating circumstances. Unfortunately, there is not a way to avoid such  nuance interactions of external factors. Another challenge is the provided statistical categories is limited
and may not cover all aspects of a player’s performance. Furthermore, comparing the players across the NBA and WNBA needs careful consideration as they are two separate leagues. The
leagues have different rules, playing times, and physical demands. So a direct comparison might not take consideration the differences between the two leagues. Lastly, the data set is
solely from the 2023 WNBA season and the 2023-24 NBA season. For this reason this dataset may well not reflect a player’s true potential as it is limited to only one season. Addressing
and acknowledging these challenges and limitations will further strengthen the validity and reliability of this analysis.
### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
